version: "3.8"
services:
  backend:
    build: ./apps/backend
    networks:
      - finance-network
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://user:password@database/finance"
      JWT_SECRET: "your-secret-key"
    depends_on:
      - database

  frontend:
    build: ./apps/frontend
    networks: 
      - finance-network
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: postgres:17
    restart: always
    networks:
      - finance-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  finance-network:

